// lyrics_data.c -- auto-generated by fetch_lyrics.py
// Do not edit by hand.

#include "lyrics_data.h"
#include <string.h>

static const char s_synced_TAME_IMPALA_LET_IT_HAPPEN[] =
    "[00:27.62]It's always around me, all this noise, but\n[00:33.34]Not nearly a"
    "s loud as the voice saying\n[00:39.05]\"Let it happen, let it happen\"\n[00:"
    "44.63]\"Just let it happen, let it happen\"\n[00:56.89]All this running arou"
    "nd\n[01:00.65]Trying to cover my shadow\n[01:04.48]An ocean growing inside\n"
    "[01:08.23]Now all the others seem shallow\n[01:12.24]All this running around"
    "\n[01:16.12]Bearing down on my shoulders\n[01:19.94]I can hear an alarm\n[01"
    ":23.78]Must be morning\n[01:44.04]I heard about a whirlwind that's coming 'r"
    "ound\n[01:49.95]It's gonna carry off all that isn't bound and\n[01:55.90]Whe"
    "n it happens, when it happens\n[02:01.41]So let it happen, let it happen\n[0"
    "2:09.84]All this running around\n[02:13.70]I can't fight it much longer\n[02"
    ":17.41]Something's trying to get out\n[02:21.39]And it's never been closer\n"
    "[02:25.17]If my take-off fails\n[02:29.01]Make up some other story\n[02:32.6"
    "8]But if I never come back\n[02:36.66]Tell my mother I'm sorry\n[07:00.51]Ba"
    "by, now I'm ready, moving on\n[07:05.73]Oh, but maybe I was ready all along"
    "\n[07:11.55]Oh, I'm ready for the moment and the sound\n[07:17.30]Oh, but ma"
    "ybe I was ready all along\n[07:23.06]Oh, baby, now I'm ready, moving on\n[07"
    ":28.83]Oh, but maybe I was ready all along\n[07:34.59]Oh, I'm ready for the "
    "moment and the sound\n[07:40.40]Oh, but maybe I was ready all along\n[07:45."
    "30]";

static const char s_synced_THE_STROKES_REPTILIA[] =
    "[00:37.75] He seemed impressed by the way you came in\n[00:43.31] Tell us a"
    " story, I know you're not boring\n[00:49.87] I was afraid that you would no"
    "t insist\n[00:55.32] You sound so sleepy, just take this, now leave me\n[0"
    "1:01.09] I said: Please don't slow me down if I'm going too fast\n[01:07.1"
    "3] You're in a strange part of our town\n[01:14.88] \n[01:25.72] Yeah, the"
    " night's not over\n[01:28.97] You're not trying hard enough\n[01:33.09] Our"
    " lives are changing lanes\n[01:36.00] You ran me off the road\n[01:39.21] T"
    "he wait is over\n[01:40.82] I'm now taking over\n[01:44.02] You're no long"
    "er laughing\n[01:47.10] I'm not drowning fast enough\n[01:51.99] \n[02:15."
    "19] Now every time that I look at myself\n[02:20.36] I thought I told you,"
    " this world is not for you\n[02:26.86] The room is on fire as she's fixing"
    " her hair\n[02:32.54] You sound so angry, just calm down you found me\n[02"
    ":38.21] I said: Please don't slow me down if I'm going too fast\n[02:44.47"
    "] You're in a strange part of our town\n[02:51.16] \n[03:02.91] Yeah, the "
    "night's not over\n[03:05.82] You're not trying hard enough\n[03:10.24] Our"
    " lives are changing lanes\n[03:12.94] You ran me off the road\n[03:16.21] "
    "The wait is over\n[03:17.95] I'm now taking over\n[03:21.18] You're no lon"
    "ger laughing\n[03:24.33] I'm not drowning fast enough\n[03:27.74] ";

static const char s_synced_COLDPLAY_CLOCKS[] =
    "[00:30.06] The lights go out and I can't be saved\n[00:33.90] Tides that I t"
    "ried to swim against\n[00:37.05] Have brought me down upon my knees\n[00:41."
    "49] Oh, I beg, I beg and plead\n[00:44.08] Singin' come out of things un sai"
    "d\n[00:48.25] Shoot an apple off my head\n[00:51.41] And a trouble that can'"
    "t be named\n[00:55.27] A tiger's waiting to be tamed, singin'\n[01:00.07] \n"
    "[01:00.80] You are\n[01:08.20] You are\n[01:14.51] \n[01:28.96] Confusion th"
    "at never stops\n[01:32.26] Closing walls and ticking clocks\n[01:35.51] Gonn"
    "a come back and take you home\n[01:39.48] I could not stop that you now know"
    "\n[01:43.00] Singin' come out upon my seas\n[01:47.01] Cursed missed opportu"
    "nities\n[01:50.43] Am I a part of the cure\n[01:53.93] Or am I part of the d"
    "isease? Singin'\n[01:59.00] \n[01:59.48] You are\n[02:06.83] You are\n[02:14"
    ".15] You are\n[02:21.70] You are\n[02:27.26] \n[02:43.48] You are\n[02:50.90"
    "] You are\n[02:56.85] \n[02:58.12] And nothing else compares\n[03:05.11] Oh,"
    " no, nothing else compares\n[03:12.61] And nothing else compares\n[03:19.53]"
    " \n[03:56.70] You are\n[04:04.09] You are\n[04:10.00] \n[04:10.05] Home, hom"
    "e, where I wanted to go\n[04:17.59] Home, home, where I wanted to go\n[04:24"
    ".91] Home, home, where I wanted to go\n[04:32.25] Home, home, where I wanted"
    " to go\n[04:39.86] ";

static const char s_synced_MUSE_PLUG_IN_BABY[] =
    "[00:31.63] I've exposed your lies, baby\n[00:37.98] The underneath's no big "
    "surprise\n[00:42.53] And now it's time for changing\n[00:49.30] And cleansin"
    "g everything\n[00:53.02] To forget your love\n[00:59.06] \n[01:01.93] My plu"
    "g in baby\n[01:06.28] Crucifies my enemies\n[01:09.78] When I'm tired of giv"
    "ing, whoa\n[01:16.76] My plug in baby\n[01:20.19] In unbroken virgin realiti"
    "es\n[01:24.33] Is tired of living, ooh\n[01:31.26] \n[01:51.58] Don't confus"
    "e\n[01:53.06] Baby, you're gonna lose your own game\n[02:00.86] Change me, r"
    "eplace the envying\n[02:08.04] To forget your love\n[02:14.05] \n[02:17.85] "
    "My plug in baby\n[02:22.05] Crucifies my enemies\n[02:24.60] When I'm tired "
    "of giving, whoa\n[02:31.86] My plug in baby\n[02:35.58] In unbroken virgin r"
    "ealities\n[02:39.51] Is tired of living, ooh\n[02:46.18] And I've seen your "
    "loving\n[02:50.25] Mine is gone\n[02:55.41] And I've been in trouble\n[03:00"
    ".53] Whoa\n[03:04.51] ";

static const char s_synced_RADIOHEAD_KARMA_POLICE[] =
    "[00:26.78]Karma police\n[00:31.00]Arrest this man\n[00:33.39]He talks in mat"
    "hs\n[00:37.46]He buzzes like a fridge\n[00:39.77]He's like a detuned radio\n"
    "[00:46.55]\n[00:52.66]Karma police\n[00:56.90]Arrest this girl\n[00:59.12]He"
    "r Hitler hairdo\n[01:03.27]Is making me feel ill\n[01:05.45]And we have cras"
    "hed her party\n[01:13.60]\n[01:18.45]This is what you get\n[01:21.79]\n[01:2"
    "4.66]This is what you get\n[01:28.00]\n[01:31.00]This is what you get\n[01:3"
    "4.56]When you mess with us\n[01:38.42]\n[01:43.58]Karma police\n[01:47.77]I'"
    "ve given all I can\n[01:50.05]It's not enough\n[01:54.23]I've given all I ca"
    "n\n[01:56.38]But we're still on the payroll\n[02:09.10]This is what you get"
    "\n[02:12.44]\n[02:15.38]This is what you get\n[02:18.90]\n[02:21.97]This is "
    "what you get\n[02:25.39]When you mess with us\n[02:31.84]\n[02:34.67]For a m"
    "inute there\n[02:37.96]I lost myself\n[02:41.15]I lost myself\n[02:47.10]Phe"
    "w, for a minute there\n[02:50.69]I lost myself\n[02:53.92]I lost myself\n[02"
    ":59.50]Ohh...\n[03:05.00]Oh...\n[03:08.25]Ohh...\n[03:11.98]For a minute the"
    "re\n[03:14.60](Yeah...)\n[03:16.19]I lost myself\n[03:17.78](Yeah...)\n[03:1"
    "9.39]I lost myself\n[03:20.96](Yeah...)\n[03:25.32]Phew, for a minute there"
    "\n[03:27.27](Yeah...)\n[03:28.90]I lost myself\n[03:30.46](Yeah...)\n[03:32."
    "14]I lost myself\n[03:33.72](Yeah...)\n[03:40.06](Yeah...)\n[03:43.18](Yeah."
    "..)\n[03:46.40](Yeah...)\n[03:52.77](Yeah...)\n[03:55.90](Yeah...)\n[03:59.1"
    "0](Yeah...)\n[04:01.16]";

const LyricsEntry g_lyrics_data[LYRICS_DATA_COUNT] = {
    { "Tame Impala", "Let It Happen", false, s_synced_TAME_IMPALA_LET_IT_HAPPEN },
    { "The Strokes", "Reptilia", false, s_synced_THE_STROKES_REPTILIA },
    { "Coldplay", "Clocks", false, s_synced_COLDPLAY_CLOCKS },
    { "Muse", "Plug In Baby", false, s_synced_MUSE_PLUG_IN_BABY },
    { "Radiohead", "Karma Police", false, s_synced_RADIOHEAD_KARMA_POLICE },
    { "C418", "Sweden", true, NULL },
};

const LyricsEntry *LyricsData_Find(const char *artist,
                                    const char *track)
{
    int i;
    for (i = 0; i < LYRICS_DATA_COUNT; i++) {
        if (strcmp(g_lyrics_data[i].artist, artist) == 0 &&
            strcmp(g_lyrics_data[i].track,  track)  == 0) {
            return &g_lyrics_data[i];
        }
    }
    return NULL;
}

