// lyrics_data.h -- auto-generated by fetch_lyrics.py
// Do not edit by hand.

#ifndef LYRICS_DATA_H_
#define LYRICS_DATA_H_

#include <stdbool.h>

typedef struct {
    const char *artist;
    const char *track;
    bool        instrumental;
    const char *synced_lyrics;  /* NULL if unavailable */
} LyricsEntry;

#define LYRICS_DATA_COUNT 8

extern const LyricsEntry g_lyrics_data[LYRICS_DATA_COUNT];

/* Look up lyrics by artist+track (case-sensitive).
   Returns NULL if not found. */
const LyricsEntry *LyricsData_Find(const char *artist,
                                    const char *track);

#endif /* LYRICS_DATA_H_ */
